--Need all stocks that beat the S&P each year, which also paid a dividend.
--Should I come up with a yearly gain metric?
--Instead of running total. use two days for each: start of year & end of year